browser:
  browserName: firefox
environment:
  test:
    envName: test
    active: false
    url: http://51.75.61.161:9102/form.php
    firstName: Mateusz
    lastName: Bukowski
    email: mbukowski2@sii.pl
    validation: Form send with success
    age: 30

  prod:
    envName: prod
    active: true
    url: http://51.75.61.161:9102/form.php
    firstName: Mateusz
    lastName: Bukowski
    email: mbukowski2@sii.pl
    validation: Form send with success
    age: 30